# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4e306799af7fc8118ce68ef42b9a88e2ae7347a329caac4984c7f4d2208fd1db5a2ebf1135930597f4dadcfb68c7f7f6e1759fc6ccd1f3dc7ecd919dfc6e963

test:
  secret_key_base: a717ca2fd5cbe1c1a7cf4d62d2965dbe5a54684510a0b7d880e0e209886283ad923f855e67cc4ec86acd18a6160c2c9088f818a3c87296472cbb2418327abf42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
